name: Executar Python i pujar JSON cada 5 minuts

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·lar dependències necessàries
        run: |
          pip install --upgrade pip
          pip install openmeteo-requests pandas requests requests-cache

      - name: Executar script Python
        run: python temperatures.py

      - name: Llistar fitxers generats
        run: ls -l temp_*.json || echo "No s'han generat fitxers .json"

      - name: Configurar Git per fer commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Afegir fitxers .json i fer commit
        run: |
          git add temp_*.json
          git commit -m "Afegit fitxer JSON generat per GitHub Actions [skip ci]" || echo "No hi ha canvis per commitar"

      - name: Configurar remote amb token
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Pujar canvis al repositori
        run: git push
